---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beets
  labels:
    app: beets
  annotations:
    link.argocd.argoproj.io/external-link: http://media.beets
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: beets
  template:
    metadata:
      labels:
        app: beets
    spec:
      containers:
        - name: beets
          image: linuxserver/beets:latest
          envFrom:
            - configMapRef:
                name: beets-cm
          ports:
            - name: web
              containerPort: 8337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8337
              scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              initialDelaySeconds: 20
          startupProbe:
            httpGet:
              path: /
              port: 8337
              scheme: HTTP
              timeoutSeconds: 2
              periodSeconds: 20
              initialDelaySeconds: 60
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /music
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: beets-storage
        - name: library
          persistentVolumeClaim:
            claimName: music-storage
        - name: downloads
          persistentVolumeClaim:
            claimName: music-downloads
