---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-gen
  labels:
    app: rss-gen
  annotations:
    link.argocd.argoproj.io/external-link: http://gen.rss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rss-gen
  template:
    metadata:
      labels:
        app: rss-gen
    spec:
      containers:
        - name: rss-gen
          image: damoeb/rss-proxy:2.0.0-beta
          envFrom:
            - configMapRef:
                name: rssgen-cm
            - secretRef:
                name: rssgen-vars
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "64m"
              memory: "128Mi"
            limits:
              cpu: "128m"
              memory: "256Mi"
        - name: richpuppeteer
          image: damoeb/rich-rss:puppeteer-0.1
          ports:
            - name: richpuppeteer
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 60
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 3
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            initialDelaySeconds: 60
            failureThreshold: 30
          resources:
            requests:
              cpu: "64m"
              memory: "128Mi"
            limits:
              cpu: "128m"
              memory: "256Mi"
