version: '3'
vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  PATH_ERROR: is not installed or correctly configured in PATH.

silent: true

tasks:
  init:
    dir: terraform
    cmds:
    - terraform init -upgrade -backend-config="conn_str=${TF_CONN_STR}"

  init:vault:
    dir: terraform/modules/vault
    cmds:
    - terraform init -upgrade -backend-config="conn_str=${TF_CONN_STR}"

  init:unifi:
    dir: terraform/modules/unifi
    cmds:
    - terraform init -upgrade -backend-config="conn_str=${TF_CONN_STR}"

  init:vultr:
    dir: terraform/modules/vultr
    cmds:
    - terraform init -upgrade -backend-config="conn_str=${TF_CONN_STR}"

  plan:
    dir: terraform
    cmds:
    - terraform plan

  plan:vault:
    dir: terraform/modules/vault
    cmds:
    - terraform plan

  plan:unifi:
    dir: terraform/modules/unifi
    cmds:
    - terraform plan

  plan:vultr:
    dir: terraform/modules/vultr
    cmds:
    - terraform plan

  apply:
    dir: terraform
    cmds:
    - terraform apply -auto-approve

  apply:vault:
    dir: terraform/modules/vault
    cmds:
    - terraform apply -auto-approve

  apply:unifi:
    dir: terraform/modules/unifi
    cmds:
    - terraform apply -auto-approve

  apply:vultr:
    dir: terraform/modules/vultr
    cmds:
    - terraform apply -auto-approve

  destroy:
    dir: terraform
    cmds:
    - terraform destroy -auto-approve

  destroy:vault:
    dir: terraform/modules/vault
    cmds:
    - terraform destroy -auto-approve

  destroy:vultr:
    dir: terraform/modules/vultr
    cmds:
    - terraform destroy -auto-approve

  docs:
    cmds:
    - terraform-docs markdown -c ./terraform/.terraform-docs.yaml ./terraform --output-file README.md
    - terraform-docs markdown -c ./terraform/.terraform-docs.yaml ./terraform/modules/vault --output-file README.md
    - terraform-docs markdown -c ./terraform/.terraform-docs.yaml ./terraform/modules/unifi --output-file README.md
    - terraform-docs markdown -c ./terraform/.terraform-docs.yaml ./terraform/modules/vultr --output-file README.md
