apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/wavyland/wavy/1e45bf3a20838814bb466c4b7bcb101389ecb947/manifests/webhook.yaml

patchesStrategicMerge:
- overlay/namespace-delete.yaml
- overlay/patch-deploy.yaml
- overlay/patch-job.yaml
- overlay/patch-rb.yaml
- overlay/patch-crb.yaml

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: cert-gen
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
        value: BeforeHookCreation
  - target:
      version: v1
      kind: ClusterRole
      name: wavy-webhook
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync
  - target:
      version: v1
      kind: ClusterRoleBinding
      name: wavy-webhook
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync
  - target:
      version: v1
      kind: RoleBinding
      name: wavy-webhook
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync
  - target:
      version: v1
      kind: Role
      name: wavy-webhook
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync

namespace: utilities

commonAnnotations:
  reloader.stakater.com/auto: "true"
