apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
- https://github.com/gruberdev/homelab/apps/networking/cloudflared
- https://github.com/gruberdev/homelab/apps/networking/tailscale

patchesStrategicMerge:
- overlay/cloudflared-cm.yaml

namespace: rss

patches:
- path: https://raw.githubusercontent.com/gruberdev/homelab/main/apps/networking/tailscale/patch.yaml
  target:
    kind: Deployment
    name: rss-gen
- patch: |-
    - op: replace
      path: "/spec/template/spec/volumes/0/secret/secretName"
      value: "rss-tunnel"
  target:
    kind: Deployment
    name: cloudflared
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/2"
      value:
        name: TS_HOSTNAME
        value: "gen.rss"
    - op: replace
      path: "/spec/template/spec/containers/0/env/3"
      value:
        name: DEST_PORT
        value: "8080"
  target:
    kind: Deployment
    name: rss-gen
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: node-four
  target:
    kind: Deployment
    name: rss-gen

commonAnnotations:
  reloader.stakater.com/auto: "true"
