apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wger
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gym.gruber.dev.br
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: gym.gruber.dev.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wger-tailscale
            port:
              number: 80
  tls:
  - hosts:
    - gym.gruber.dev.br
    secretName: wger-tls
