apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanoshi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: read.gruber.dev.br
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: read.gruber.dev.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tanoshi-svc
            port:
              name: web
  tls:
  - hosts:
    - read.gruber.dev.br
    secretName: tanoshi-tls
