apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/zilliztech/milvus-operator/v0.8.1/deploy/manifests/deployment.yaml

patchesStrategicMerge:
- overlay/milvus-deployment.yaml
- overlay/milvus-job.yaml
- overlay/namespace-delete.yaml

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: milvus-operator-checker
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
        value: HookSucceeded

namespace: milvus-operator
