apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: change-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: onchange.gruber.dev.br
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tailscale.com/hostname: "onchange"
spec:
  ingressClassName: tailscale
  rules:
  - host: onchange.gruber.dev.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: change-svc
            port:
              name: web
  tls:
  - hosts:
    - onchange.gruber.dev.br
    secretName: onchange-tlse
