apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- fleet.yaml
- fleetautoscaler.yaml
- gameserver.yaml
- gameserverset.yaml
- gameserverallocationpolicy.yaml
- apiservice.yaml
