---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
  annotations:
    link.argocd.argoproj.io/external-link: http://adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      hostNetwork: true
      initContainers:
        - name: copy-configmap
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "mkdir -p /opt/adguardhome/conf && cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml"
          volumeMounts:
            - name: adguard-home-configmap
              mountPath: /tmp
            - name: adguard-home-config
              mountPath: /opt/adguardhome/conf
          securityContext:
            runAsUser: 0
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.18
          env:
            - name: TZ
              value: "America/Sao_Paulo"
          args:
            - "-c"
            - "/opt/adguardhome/conf/AdGuardHome.yaml"
            - "--work-dir"
            - "/opt/adguardhome/work"
            - "--no-check-update"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 853
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: adguard-home-config
              mountPath: /opt/adguardhome/conf
            - name: adguard-home-logs
              mountPath: /opt/adguardhome/work
        - name: exporter
          image: ebrianne/adguard-exporter:latest
          ports:
          - name: metrics
            containerPort: 9617
            protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: adguard-exporter
            - secretRef:
                name: adguard-exporter
      volumes:
        - name: adguard-home-configmap
          configMap:
            name: adguard-home
            items:
              - key: AdGuardHome.yaml
                path: AdGuardHome.yaml
        - name: adguard-home-config
          persistentVolumeClaim:
            claimName: adguard-storage
        - name: adguard-home-logs
          persistentVolumeClaim:
            claimName: adguard-logs
