apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cr.yaml
- crb.yaml
- rb.yaml
- cm.yaml
- deployment.yaml
- ingressclass.yaml
- svc.yaml
- role.yaml
- sa.yaml
- ./admission-webhooks

namespace: ingress
