name: Automated PRs on new branch push
on:
  push:
    branches-ignore:
    - main

jobs:
  auto-fix-pr:
    name: Automated new "fix" tagged branch
    runs-on: ubuntu-latest
    steps:
      - name: Generate branch name
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7
        id: set-branch-name
        with:
          script: |
            const capitalize = (name) => name.charAt(0).toUpperCase() + name.slice(1);
            const category = context.payload.ref.startsWith("refs/heads/fix")
              ? "`[Fix]`"
              : "";
            return `${category} ${capitalize(
              context.payload.ref
                .replace("refs/heads/", "")
                .replace(/-/g, " ")
                .replace("fix/", "")
            )}`;
          result-encoding: string
      - name: Set branch name
        run: echo "PULL_REQUEST_TITLE=${{steps.set-branch-name.outputs.result}}" >> $GITHUB_ENV
      - name: pull-request-action;'p'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feat/"
          PULL_REQUEST_BRANCH: "main"
      - name: Generate PR body
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7
        id: set-pr-body
        with:
          script: |
            return `Author: @${context.payload.head_commit.author.username
            } with ${context.payload.commits.length} commit${
              context.payload.commits.length === 1 ? "" : "s"
            }.`;
          result-encoding: string
      - name: Set PR body
        run: echo "PULL_REQUEST_BODY=${{steps.set-pr-body.outputs.result}}" >> $GITHUB_ENV
      - name: pull-request-action
        uses: vsoch/pull-request-action@f9e7f419d6b44935f6b0458fad17077269caaf71 # 1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: fix
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_REVIEWERS: gruberdev
  auto-feat-pr:
    name: Automated new "app" or "feat" tagged branch
    runs-on: ubuntu-latest
    steps:
      - name: Generate branch name
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7
        id: set-branch-name
        with:
          script: |
            const capitalize = (name) => name.charAt(0).toUpperCase() + name.slice(1);
            const category = context.payload.ref.startsWith("refs/heads/feat")
              ? "[New App]"
              : context.payload.ref.startsWith("refs/heads/app")
              ? "`[New App]`"
              : "";
            return `${category} ${capitalize(
              context.payload.ref
                .replace("refs/heads/", "")
                .replace(/-/g, " ")
                .replace("feat/", "")
                .replace("app/", "")
            )}`;
          result-encoding: string
      - name: Set branch name
        run: echo "PULL_REQUEST_TITLE=${{steps.set-branch-name.outputs.result}}" >> $GITHUB_ENV
      - name: pull-request-action;'p'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feat/"
          PULL_REQUEST_BRANCH: "main"
      - name: Generate PR body
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7
        id: set-pr-body
        with:
          script: |
            return `Author: @${context.payload.head_commit.author.username
            } with ${context.payload.commits.length} commit${
              context.payload.commits.length === 1 ? "" : "s"
            }.`;
          result-encoding: string
      - name: Set PR body
        run: echo "PULL_REQUEST_BODY=${{steps.set-pr-body.outputs.result}}" >> $GITHUB_ENV
      - name: pull-request-action
        uses: vsoch/pull-request-action@f9e7f419d6b44935f6b0458fad17077269caaf71 # 1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: feat
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_REVIEWERS: gruberdev
