name: Sync Tailscale

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  acl-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if Tailscale file has changed
        id: tailscale-changes
        uses: tj-actions/changed-files@25ef3926d147cd02fc7e931c1ef50772bbb0d25d # v40
        with:
          files: |
            policy.hujson

      - uses: actions/checkout@v4
      - name: Sync ACL with Tailscale
        if: github.event_name == 'push' && steps.tailscale-changes.outputs.any_changed == 'true'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply

      - name: Test newer ACL configs
        if: github.event_name == 'pull_request' && steps.tailscale-changes.outputs.any_changed == 'true'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
