apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archivebox
  annotations:
    external-dns.alpha.kubernetes.io/hostname: archive.xn--qck4cud2cb.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: archive.xn--qck4cud2cb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actual
            port:
              name: web
  tls:
  - hosts:
    - archive.xn--qck4cud2cb.com
    secretName: archive-tls
